version: '3'
services:
  backend:
    init: true
    restart: always
    build: ./backend
    command: npm start
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mongo

  frontend:
    init: true
    build: ./frontend/stream-ui
    command: npm start
    volumes:
      - ./frontend/stream-ui:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    init: true
    logging:
      driver: none
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db

  mongo-express:
    init: true
    logging:
      driver: none
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

volumes:
  data: